### PR TITLE
Fix displaying bite

### PR DESCRIPTION
**Pull request by rhelmstedter**
I ran across an error when displaying a bite in the terminal. When we changed everything to return Bite objects, I forgot to update the display command. Then, when I ran the tests, I noticed two were broken. I never patched `LOCAL_BITES_DB` so it always pulled from by actual pybites dir. Now that I updated it, the bite I was testing was missing. This should work.

@bbelderbos did you still want to change the test bite from "rotate string characters" to a free one? We could do it in this pull request.

### CODE REVIEW

**Comment by bbelderbos** [comment]
Thanks, I will review and merge on Monday. I don't mind the Bite for now. We can provide access or make it a free one.

**Comment by bbelderbos** [comment]
@rhelmstedter thanks, before merging this, thinking maintainability / scalability, would it take much effort to change the e2e test bite to a free intro bite please? Thanks.

**Comment by rhelmstedter** [comment]
I'll take a look this weekend. I don't think it will be that difficult.

**Comment by bbelderbos** [comment]
ok thanks

**Comment by rhelmstedter** [comment]
This should do it. All of the testing now uses the first two regular bites: Sum n numbers and Parse a list of names.

**Review by bbelderbos — APPROVED** [review]
Thanks, looks good!

**Comment by bbelderbos** [comment]
oops build before merge so 1.1.4 is now up there without these changes
will now pull and make this 1.1.5 then and push that up to PyPI as well ...

**Comment by bbelderbos** [comment]
done

**Pull request merged**
